worker_processes 1;
worker_rlimit_nofile 4096;

events {
    worker_connections 2048;
    use epoll;
    multi_accept on;
}

http {
    access_log off;
    error_log /dev/null;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 30;
    keepalive_requests 1000;
    
    # Optimize buffer sizes
    client_body_buffer_size 1k;
    client_max_body_size 1k;
    large_client_header_buffers 2 1k;

    upstream backend {
        least_conn;
        server api-01:8080 max_fails=1 fail_timeout=1s;
        server api-02:8080 max_fails=1 fail_timeout=1s;
        keepalive 300;
        keepalive_requests 1000;
        keepalive_timeout 60s;
    }

    server {
        listen 9999;
        
        location / {
            proxy_pass http://backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "keep-alive";
            proxy_connect_timeout 60ms;
            proxy_send_timeout 300ms;
            proxy_read_timeout 1000ms;
            proxy_buffering off;
            proxy_request_buffering off;
        }
    }
}